### ISSUE TITLE
Non original song - download error

### ISSUE THREAD

**Issue by Xerl0x** [FelixGail/PlayMusicDownloader#7]
Self uploaded songs without any specifications (artist, title...) are creating an error.

```
[88%]  Song 'Animal Style by Biffy Clyro' already present in target directory.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Xerl0x\Documents\PlayMusicDownloader-master\main.py", line 98, in run
    self.download()
  File "C:\Users\Xerl0x\Documents\PlayMusicDownloader-master\main.py", line 105, in download
    info = Decoder(self.assigned_song['track'], 'UTF-16')
KeyError: 'track'

[88%]  Song 'Leave Me Alone by FIDLAR' already present in target directory.
```

**Comment by FelixGail** [comment]
Error still present. Self added songs don't have the information saved in key 'track'
